<?php
declare(strict_types=1);

return [
    ['GET', '/', 'PublicController@index', ['Security']],
    ['GET', '/menus', 'PublicController@menusPage', ['Security']],
    ['GET', '/menus/filter', 'PublicController@filterMenus', ['Security']],
    ['GET', '/menus/{id}', 'PublicController@menuDetail', ['Security']],
    ['GET', '/public/menus', 'PublicController@getMenus', ['Security']],
    ['GET', '/public/menus/{id}', 'PublicController@getMenuById', ['Security']],
    ['GET', '/contact', 'ContactController@index', ['Security']],
    ['POST', '/contact', 'ContactController@send', ['Security']],
    ['GET', '/api/address/autocomplete', 'AddressController@autocomplete', ['Security']],
    ['GET', '/quote', 'QuoteController@index', ['Security']],
    ['POST', '/quote', 'QuoteController@submit', ['Security']],
    ['GET', '/legal', 'PublicController@legal', ['Security']],
    ['GET', '/cgv', 'PublicController@cgv', ['Security']],

    ['GET', '/login', 'AuthController@showLogin', ['Security', 'Guest']],
    ['POST', '/login', 'AuthController@login', ['Security', 'Guest']],
    ['GET', '/register', 'AuthController@showRegister', ['Security', 'Guest']],
    ['POST', '/register', 'AuthController@register', ['Security', 'Guest']],
    ['GET', '/profile', 'AuthController@profile', ['Security', 'Auth']],
    ['POST', '/profile', 'AuthController@updateProfile', ['Security', 'Auth']],
    ['POST', '/password', 'AuthController@changePassword', ['Security', 'Auth']],
    ['POST', '/logout', 'AuthController@logout', ['Security', 'Auth']],
    ['GET', '/forgot-password', 'AuthController@showForgotPassword', ['Security', 'Guest']],
    ['POST', '/forgot-password', 'AuthController@forgotPassword', ['Security', 'Guest']],
    ['GET', '/reset-password/{token}', 'AuthController@showResetPassword', ['Security', 'Guest']],
    ['POST', '/reset-password/{token}', 'AuthController@resetPassword', ['Security', 'Guest']],

    ['GET', '/orders', 'OrderController@index', ['Security', 'Auth']],
    ['GET', '/orders/new', 'OrderController@new', ['Security', 'Auth']],
    ['POST', '/orders', 'OrderController@create', ['Security', 'Auth']],
    ['GET', '/orders/confirmation/{id}', 'OrderController@confirmation', ['Security', 'Auth']],
    ['POST', '/orders/{id}/review', 'OrderController@review', ['Security', 'Auth']],
    ['POST', '/orders/{id}/edit', 'OrderController@updateCustomerOrder', ['Security', 'Auth']],
    ['POST', '/orders/{id}/status', 'OrderController@updateStatus', ['Security', 'Auth']],
    ['GET', '/notifications', 'NotificationController@index', ['Security', 'Auth']],
    ['POST', '/notifications/{id}/read', 'NotificationController@read', ['Security', 'Auth']],

    ['GET', '/admin/login', 'AdminController@showLogin', ['Security', 'Guest']],
    ['POST', '/admin/login', 'AdminController@login', ['Security', 'Guest']],
    ['GET', '/admin/dashboard', 'AdminController@dashboard', ['Security', 'Admin']],
    ['GET', '/admin/orders', 'AdminController@orders', ['Security', 'Staff']],
    ['GET', '/admin/quotes', 'AdminController@quotes', ['Security', 'Staff']],
    ['GET', '/admin/emails', 'EmailController@inbox', ['Security', 'Staff']],
    ['POST', '/admin/emails/{id}/reply', 'EmailController@reply', ['Security', 'Staff']],
    ['POST', '/admin/emails/simulate', 'EmailController@simulate', ['Security', 'Admin']],
    ['POST', '/admin/emails/test', 'EmailController@sendTest', ['Security', 'Admin']],
    ['POST', '/admin/emails/draft', 'EmailController@saveDraft', ['Security', 'Staff']],
    ['POST', '/admin/emails/send', 'EmailController@sendComposed', ['Security', 'Staff']],
    ['POST', '/admin/emails/{source}/{id}/trash', 'EmailController@trash', ['Security', 'Staff']],
    ['POST', '/admin/quotes/{id}/status', 'AdminController@updateQuoteStatus', ['Security', 'Staff']],
    ['POST', '/admin/orders/{id}/status', 'AdminController@updateOrderStatus', ['Security', 'Staff']],
    ['GET', '/admin/hours', 'AdminController@openingHours', ['Security', 'Staff']],
    ['POST', '/admin/hours', 'AdminController@updateOpeningHours', ['Security', 'Staff']],
    ['GET', '/admin/dishes', 'AdminController@dishes', ['Security', 'Staff']],
    ['POST', '/admin/dishes', 'AdminController@createDish', ['Security', 'Staff']],
    ['POST', '/admin/dishes/{id}/edit', 'AdminController@updateDish', ['Security', 'Staff']],
    ['POST', '/admin/dishes/{id}/delete', 'AdminController@deleteDish', ['Security', 'Staff']],
    ['GET', '/admin/customers', 'AdminController@customers', ['Security', 'Staff']],
    ['POST', '/admin/customers/{id}/disable', 'AdminController@disableCustomer', ['Security', 'Staff']],
    ['POST', '/admin/customers/{id}/enable', 'AdminController@enableCustomer', ['Security', 'Staff']],
    ['GET', '/admin/employees', 'AdminController@getEmployees', ['Security', 'Admin']],
    ['POST', '/admin/employees', 'AdminController@createEmployee', ['Security', 'Admin']],
    ['POST', '/admin/employees/{id}/disable', 'AdminController@disableEmployee', ['Security', 'Admin']],
    ['POST', '/admin/employees/{id}/enable', 'AdminController@enableEmployee', ['Security', 'Admin']],
    ['GET', '/admin/menus', 'AdminController@getMenus', ['Security', 'Staff']],
    ['POST', '/admin/menus', 'AdminController@createMenu', ['Security', 'Staff']],
    ['POST', '/admin/menus/{id}', 'AdminController@updateMenu', ['Security', 'Staff']],
    ['DELETE', '/admin/menus/{id}', 'AdminController@deleteMenu', ['Security', 'Staff']],
    ['POST', '/admin/menus/{id}/delete', 'AdminController@deleteMenu', ['Security', 'Staff']],
    ['GET', '/admin/comments/pending', 'AdminController@getPendingComments', ['Security', 'Staff']],
    ['POST', '/admin/comments/{id}/validate', 'AdminController@validateComment', ['Security', 'Staff']],
    ['POST', '/admin/comments/{id}/reject', 'AdminController@rejectComment', ['Security', 'Staff']],
    ['GET', '/admin/revenue', 'AdminController@revenuePage', ['Security', 'Admin']],
    ['GET', '/admin/revenue/menu', 'AdminController@revenueByMenu', ['Security', 'Admin']],
];